default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twi_app_development

test:
  <<: *default
  database: twi_app_test

production:
  <<: *default
  database: twi_app_production
  username: twi_app
  password: <%= ENV['TWI_APP_DATABASE_PASSWORD'] %>
